/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsConditionsRouteImport } from './routes/terms-conditions'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsMedicalBayRouteImport } from './routes/projects.medical-bay'
import { Route as ProjectsLunjaVillageRouteImport } from './routes/projects.lunja-village'
import { Route as ProjectsEidenAcademyRouteImport } from './routes/projects.eiden-academy'
import { Route as ProjectsEducazenKidsRouteImport } from './routes/projects.educazen-kids'
import { Route as ProjectsDmcMoroccoRouteImport } from './routes/projects.dmc-morocco'
import { Route as ProjectsBopassageRouteImport } from './routes/projects.bopassage'

const TermsConditionsRoute = TermsConditionsRouteImport.update({
  id: '/terms-conditions',
  path: '/terms-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsMedicalBayRoute = ProjectsMedicalBayRouteImport.update({
  id: '/projects/medical-bay',
  path: '/projects/medical-bay',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsLunjaVillageRoute = ProjectsLunjaVillageRouteImport.update({
  id: '/projects/lunja-village',
  path: '/projects/lunja-village',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsEidenAcademyRoute = ProjectsEidenAcademyRouteImport.update({
  id: '/projects/eiden-academy',
  path: '/projects/eiden-academy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsEducazenKidsRoute = ProjectsEducazenKidsRouteImport.update({
  id: '/projects/educazen-kids',
  path: '/projects/educazen-kids',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsDmcMoroccoRoute = ProjectsDmcMoroccoRouteImport.update({
  id: '/projects/dmc-morocco',
  path: '/projects/dmc-morocco',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsBopassageRoute = ProjectsBopassageRouteImport.update({
  id: '/projects/bopassage',
  path: '/projects/bopassage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/projects/bopassage': typeof ProjectsBopassageRoute
  '/projects/dmc-morocco': typeof ProjectsDmcMoroccoRoute
  '/projects/educazen-kids': typeof ProjectsEducazenKidsRoute
  '/projects/eiden-academy': typeof ProjectsEidenAcademyRoute
  '/projects/lunja-village': typeof ProjectsLunjaVillageRoute
  '/projects/medical-bay': typeof ProjectsMedicalBayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/projects/bopassage': typeof ProjectsBopassageRoute
  '/projects/dmc-morocco': typeof ProjectsDmcMoroccoRoute
  '/projects/educazen-kids': typeof ProjectsEducazenKidsRoute
  '/projects/eiden-academy': typeof ProjectsEidenAcademyRoute
  '/projects/lunja-village': typeof ProjectsLunjaVillageRoute
  '/projects/medical-bay': typeof ProjectsMedicalBayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/projects/bopassage': typeof ProjectsBopassageRoute
  '/projects/dmc-morocco': typeof ProjectsDmcMoroccoRoute
  '/projects/educazen-kids': typeof ProjectsEducazenKidsRoute
  '/projects/eiden-academy': typeof ProjectsEidenAcademyRoute
  '/projects/lunja-village': typeof ProjectsLunjaVillageRoute
  '/projects/medical-bay': typeof ProjectsMedicalBayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy-policy'
    | '/terms-conditions'
    | '/projects/bopassage'
    | '/projects/dmc-morocco'
    | '/projects/educazen-kids'
    | '/projects/eiden-academy'
    | '/projects/lunja-village'
    | '/projects/medical-bay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/terms-conditions'
    | '/projects/bopassage'
    | '/projects/dmc-morocco'
    | '/projects/educazen-kids'
    | '/projects/eiden-academy'
    | '/projects/lunja-village'
    | '/projects/medical-bay'
  id:
    | '__root__'
    | '/'
    | '/privacy-policy'
    | '/terms-conditions'
    | '/projects/bopassage'
    | '/projects/dmc-morocco'
    | '/projects/educazen-kids'
    | '/projects/eiden-academy'
    | '/projects/lunja-village'
    | '/projects/medical-bay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsConditionsRoute: typeof TermsConditionsRoute
  ProjectsBopassageRoute: typeof ProjectsBopassageRoute
  ProjectsDmcMoroccoRoute: typeof ProjectsDmcMoroccoRoute
  ProjectsEducazenKidsRoute: typeof ProjectsEducazenKidsRoute
  ProjectsEidenAcademyRoute: typeof ProjectsEidenAcademyRoute
  ProjectsLunjaVillageRoute: typeof ProjectsLunjaVillageRoute
  ProjectsMedicalBayRoute: typeof ProjectsMedicalBayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-conditions': {
      id: '/terms-conditions'
      path: '/terms-conditions'
      fullPath: '/terms-conditions'
      preLoaderRoute: typeof TermsConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/medical-bay': {
      id: '/projects/medical-bay'
      path: '/projects/medical-bay'
      fullPath: '/projects/medical-bay'
      preLoaderRoute: typeof ProjectsMedicalBayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/lunja-village': {
      id: '/projects/lunja-village'
      path: '/projects/lunja-village'
      fullPath: '/projects/lunja-village'
      preLoaderRoute: typeof ProjectsLunjaVillageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/eiden-academy': {
      id: '/projects/eiden-academy'
      path: '/projects/eiden-academy'
      fullPath: '/projects/eiden-academy'
      preLoaderRoute: typeof ProjectsEidenAcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/educazen-kids': {
      id: '/projects/educazen-kids'
      path: '/projects/educazen-kids'
      fullPath: '/projects/educazen-kids'
      preLoaderRoute: typeof ProjectsEducazenKidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/dmc-morocco': {
      id: '/projects/dmc-morocco'
      path: '/projects/dmc-morocco'
      fullPath: '/projects/dmc-morocco'
      preLoaderRoute: typeof ProjectsDmcMoroccoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/bopassage': {
      id: '/projects/bopassage'
      path: '/projects/bopassage'
      fullPath: '/projects/bopassage'
      preLoaderRoute: typeof ProjectsBopassageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsConditionsRoute: TermsConditionsRoute,
  ProjectsBopassageRoute: ProjectsBopassageRoute,
  ProjectsDmcMoroccoRoute: ProjectsDmcMoroccoRoute,
  ProjectsEducazenKidsRoute: ProjectsEducazenKidsRoute,
  ProjectsEidenAcademyRoute: ProjectsEidenAcademyRoute,
  ProjectsLunjaVillageRoute: ProjectsLunjaVillageRoute,
  ProjectsMedicalBayRoute: ProjectsMedicalBayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
